---
abstract: 'Automatically set update and create user id fields'
author:
  - 'Matt S. Trout     <mst@shadowcatsystems.co.uk>'
build_requires:
  Class::Accessor::Grouped: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-UserStamp
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0
tests: t/*.t
version: 0.10
